type Org = {
  group_name: string;
  office_id: string;
  office_name: string;
  contract_id: string;
  organization_id: string;
  source_anelto_username: string;
  source_anelto_password: string;
  dest_anelto_username: string;
  dest_anelto_password: string;
}

export const org_data: Org[] = [
  {
    group_name: "Nsight",
    office_id: "ABAV",
    office_name: "Anibal Avila MD PC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "b1ce429f-a1aa-433c-9e99-0aa33c76fb77",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtAbav",
    dest_anelto_password: "RwH-4f7-gCp-F1A"
  },
  {
    group_name: "Nsight",
    office_id: "AHVM",
    office_name: "Advanced Heart and Vascular Medicine",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "e44a0a74-e8fd-4b3c-8773-a92d5227419b",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtAhvm",
    dest_anelto_password: "RwH-4f7-gCp-g5E"
  },
  {
    group_name: "Nsight",
    office_id: "ANES",
    office_name: "Anesu Restorative Care, LLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "97241940-45b5-412f-9353-92d53d0dc42e",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtAnes",
    dest_anelto_password: "RwH-4f7-gCp-TtG"
  },
  {
    group_name: "Nsight",
    office_id: "ARKA",
    office_name: "Arika Gupta MD, Inc",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "5eb40556-e4ac-4638-83c5-59abc73f9f06",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtArka",
    dest_anelto_password: "RwH-4f7-gCp-VvI"
  },
  {
    group_name: "Nsight",
    office_id: "ATUM",
    office_name: "All Time Urgent and Medical Care LTD",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "ea8e2cbb-62ec-4e3e-b947-d6331c54fd6a",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtAtum",
    dest_anelto_password: "RwH-4f7-gCp-4mN"
  },
  {
    group_name: "Nsight",
    office_id: "BECS",
    office_name: "Bluegrass Extended Care Services LLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "432bcef5-95d4-4d26-8664-11dffb504b3e",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtBecs",
    dest_anelto_password: "RwH-4f7-gCp-UuH"
  },
  {
    group_name: "Nsight",
    office_id: "BEMG",
    office_name: "Bea Medical Group, Inc",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "6a628e73-5764-451a-b42d-44a7b94f2dcf",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtBemg",
    dest_anelto_password: "RwH-4f7-gCp-e2b"
  },
  {
    group_name: "Nsight",
    office_id: "BENT",
    office_name: "Bentley Heart",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "3d351a30-0e29-4248-ba39-d7b2320e22f7",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtBent",
    dest_anelto_password: "RwH-4f7-gCp-SsF"
  },
  {
    group_name: "Nsight",
    office_id: "BMPH",
    office_name: "BM Physicians LLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "63d6becc-daa8-4492-acf0-79d15dbda064",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtBmph",
    dest_anelto_password: "RwH-4f7-gCp-KkX"
  },
  {
    group_name: "Nsight",
    office_id: "BRZS",
    office_name: "Brazos Primary Care Associates",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "148ec942-8d03-425c-8c91-8948194d680f",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtBrzs",
    dest_anelto_password: "RwH-4f7-gCp-G4d"
  },
  {
    group_name: "Nsight",
    office_id: "BTLA",
    office_name: "BTLA VI",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "09bc975d-f614-4c09-b156-e1a03d572dd0",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtBtla",
    dest_anelto_password: "RwH-4f7-gCp-n4D"
  },
  {
    group_name: "Nsight",
    office_id: "CAIA",
    office_name: "CAI NCP East Mesa JV, LLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "da617aef-bc18-445c-a983-d3337b0470ab",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtCaia",
    dest_anelto_password: "RwH-4f7-gCp-3xY"
  },
  {
    group_name: "Nsight",
    office_id: "CFAM",
    office_name: "Central Phoenix Family Medicine",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "5209ee1b-36fb-483b-a037-4bbeffa73df4",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtCfam",
    dest_anelto_password: "RwH-4f7-gCp-BcC"
  },
  {
    group_name: "Nsight",
    office_id: "CFHH",
    office_name: "Center for the Healthy Heart",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "0816bd64-b65c-4e43-9c6e-96c08893594b",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtCfhh",
    dest_anelto_password: "RwH-4f7-gCp-8ar"
  },
  {
    group_name: "Nsight",
    office_id: "CROF",
    office_name: "Coshocton Regional Medical Center Family Care Clinic",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "1c36b9f2-d4c6-43f5-8c02-7296b7bbf678",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtCrof",
    dest_anelto_password: "RwH-4f7-gCp-KvN"
  },
  {
    group_name: "Nsight",
    office_id: "CKHS",
    office_name: "Connecticut Kidney & Hypertension Specialists, LLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "96107055-9c49-4ba5-a373-90833d91be67",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtCkhs",
    dest_anelto_password: "RwH-4f7-gCp-N1A"
  },
  {
    group_name: "Nsight",
    office_id: "CLBS",
    office_name: "Columbus Medical Center PC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "d9634a69-eda4-4edd-b8d6-6d04e4ee30c5",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtClbs",
    dest_anelto_password: "RwH-4f7-gCp-4Jk"
  },
  {
    group_name: "Nsight",
    office_id: "CLER",
    office_name: "CLERMONT MEDICAL CENTER, PA",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "71bc9c9d-a2dd-478e-961d-a4a173c91ad0",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtCler",
    dest_anelto_password: "RwH-4f7-gCp-WwJ"
  },
  {
    group_name: "Nsight",
    office_id: "CNBR",
    office_name: "Central Nebraska Medical Clinic",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "9972d8a8-b7d0-4ec7-8e7b-cbd8f65e7c53",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtCnbr",
    dest_anelto_password: "RwH-4f7-gCp-EfI"
  },
  {
    group_name: "Nsight",
    office_id: "CPFM",
    office_name: "Cape Family Care, LLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "b12a2db5-f392-4665-b8d5-9076c916e20c",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtCpfm",
    dest_anelto_password: "RwH-4f7-gCp-g3C"
  },
  {
    group_name: "Nsight",
    office_id: "CRCL",
    office_name: "Cardiology Clinic, Inc.",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "4e0c4b64-1dfd-4050-b32c-6af149c708f7",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtCrcl",
    dest_anelto_password: "RwH-4f7-gCp-G2b"
  },
  {
    group_name: "Nsight",
    office_id: "CRDH",
    office_name: "CardioHealth",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "92ed2758-7c0b-4f66-be1f-e1932c9fc530",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtCrdh",
    dest_anelto_password: "RwH-4f7-gCp-AbA"
  },
  {
    group_name: "Nsight",
    office_id: "CRNY",
    office_name: "Carney Family Practice",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "20ca624c-9683-4eb1-98b6-18fe88512985",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtCrny",
    dest_anelto_password: "RwH-4f7-gCp-3Ce"
  },
  {
    group_name: "Nsight",
    office_id: "CROA",
    office_name: "Coshocton Regional Medical Center Arrowhead Clinic",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "269cf6a3-274f-4f67-812d-0a3d530ad7d6",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtCroa",
    dest_anelto_password: "RwH-4f7-gCp-N3c"
  },
  {
    group_name: "Nsight",
    office_id: "CROP",
    office_name: "Coshocton Regional Medical Center Pulmonary Services",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "e0b0de4f-2119-4959-a903-861baf9a9c52",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtCrop",
    dest_anelto_password: "RwH-4f7-gCp-FgK"
  },
  {
    group_name: "Nsight",
    office_id: "DLVN",
    office_name: "Daniel Levitan, MD INC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "a9bfcb3c-b00f-45b8-9142-0f3c90626e70",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtDlvn",
    dest_anelto_password: "RwH-4f7-gCp-1bC"
  },
  {
    group_name: "Nsight",
    office_id: "DNCW",
    office_name: "Donald Cedric Wallerson, MD",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "7f8b45d8-744e-4d2c-8067-73f0a274908d",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtDncw",
    dest_anelto_password: "RwH-4f7-gCp-GgT"
  },
  {
    group_name: "Nsight",
    office_id: "DVEL",
    office_name: "David P Ellent, PLLC.",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "a188e865-36d6-4495-ac56-1642dd92a358",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtDvel",
    dest_anelto_password: "RwH-4f7-gCp-M1a"
  },
  {
    group_name: "Nsight",
    office_id: "DZEB",
    office_name: "David Zebrack D.O.",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "7ff0be9e-f7e7-4895-a033-25e48420c6a1",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtDzeb",
    dest_anelto_password: "RwH-4f7-gCp-QoO"
  },
  {
    group_name: "Nsight",
    office_id: "EFGH",
    office_name: "Effinger Health PA",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "fa0ff798-6450-4af7-a63d-027bc0b71052",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtEfgh",
    dest_anelto_password: "RwH-4f7-gCp-HhU"
  },
  {
    group_name: "Nsight",
    office_id: "EGHC",
    office_name: "E AND G HEALTHCARE, NP IN FAMILY HEALTH P.L.L.C.",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "c696ca91-a42a-478a-93f8-60ac3bf6e1a5",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtEghc",
    dest_anelto_password: "RwH-4f7-gCp-d2B"
  },
  {
    group_name: "Nsight",
    office_id: "ESPM",
    office_name: "East Side Primary Medical Care, P.C.",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "357d9078-7c01-4a34-bd1d-d3af054587a1",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtEspm",
    dest_anelto_password: "RwH-4f7-gCp-2gF"
  },
  {
    group_name: "Nsight",
    office_id: "ETLA",
    office_name: "Estrella Nephrology & Hypertension",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "145b5bb6-fae8-4702-b218-6d5e39d060e0",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtEtla",
    dest_anelto_password: "RwH-4f7-gCp-2Dc"
  },
  {
    group_name: "Nsight",
    office_id: "FLMR",
    office_name: "Fillmore County Medical Center, P.C.",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "2c233c94-3d3d-4060-9c1a-9c631491eb32",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtFlmr",
    dest_anelto_password: "RwH-4f7-gCp-m5E"
  },
  {
    group_name: "Nsight",
    office_id: "FRCN",
    office_name: "First Coast Nephrology",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "84577ad3-2585-4fd5-b543-b091dad6f614",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtFrcn",
    dest_anelto_password: "RwH-4f7-gCp-ZzM"
  },
  {
    group_name: "Nsight",
    office_id: "FSON",
    office_name: "Fusion MD",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "78c7cee7-be9c-4455-bf39-7f75a2b5edb5",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtFson",
    dest_anelto_password: "RwH-4f7-gCp-9uA"
  },
  {
    group_name: "Nsight",
    office_id: "FSTR",
    office_name: "Feasterville Family Practice, LLP",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "d155eb2e-ee23-44df-9def-4007142944af",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtFstr",
    dest_anelto_password: "RwH-4f7-gCp-IiV"
  },
  {
    group_name: "Nsight",
    office_id: "HRWG",
    office_name: "Heart Wellness Group, LLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "7c2a6283-6987-46b5-ba46-fa121f28e06b",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtHrwg",
    dest_anelto_password: "RwH-4f7-gCp-JjW"
  },
  {
    group_name: "Nsight",
    office_id: "HSCC",
    office_name: "Houston Cardiac Clinic PA",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "15d345be-8d1e-464b-b730-c763b3f6b60a",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtHscc",
    dest_anelto_password: "RwH-4f7-gCp-D1A"
  },
  {
    group_name: "Nsight",
    office_id: "HWMS",
    office_name: "Hawesville Medical Specialists PLLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "72c1b6ed-9e6c-443c-bc10-37b8b08c39d8",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtHwms",
    dest_anelto_password: "RwH-4f7-gCp-1Ab"
  },
  {
    group_name: "Nsight",
    office_id: "IAPM",
    office_name: "Interventional Anesthesia & Pain management clinic, Inc.",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "5951d0b4-4b34-4d3d-80e7-b69f3a9f0f5f",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtIapm",
    dest_anelto_password: "RwH-4f7-gCp-CcP"
  },
  {
    group_name: "Nsight",
    office_id: "IMAP",
    office_name: "Internal Medicine Associates of Plano and Frisco and Arash Tirandaz, MD PA",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "231ce4b2-dce8-49e0-9798-f83e43b35964",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtImap",
    dest_anelto_password: "RwH-4f7-gCp-LPe"
  },
  {
    group_name: "Nsight",
    office_id: "INCD",
    office_name: "Indus Cardiology",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "e76abded-5459-45cf-a566-772c71b6f587",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtIncd",
    dest_anelto_password: "RwH-4f7-gCp-LlY"
  },
  {
    group_name: "Nsight",
    office_id: "INHC",
    office_name: "Indus Healthcare",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "2fc7cb93-5bb5-4a98-95e0-4e4c8c05a950",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtInhc",
    dest_anelto_password: "RwH-4f7-gCp-b3C"
  },
  {
    group_name: "Nsight",
    office_id: "JCRL",
    office_name: "Dr. C. Jeffrey Carlson, MD, FACC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "c4e646f6-c150-446f-9f52-361585e24139",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtJcrl",
    dest_anelto_password: "RwH-4f7-gCp-YyL"
  },
  {
    group_name: "Nsight",
    office_id: "JKMC",
    office_name: "Jackson Medical Center PC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "ebcd2187-edf6-4cf2-afe2-38c5ade8054c",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtJkmc",
    dest_anelto_password: "RwH-4f7-gCp-NoA"
  },
  {
    group_name: "Nsight",
    office_id: "JPPC",
    office_name: "JAY N. PANDHI, M.D., A PROFESSIONAL CORPORATION",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "d326513c-5dde-4419-b9db-332aa893ea21",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtJppc",
    dest_anelto_password: "RwH-4f7-gCp-g1A"
  },
  {
    group_name: "Nsight",
    office_id: "JRSH",
    office_name: "John Rashkis, MD",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "edd08317-66dd-46df-b96d-74e746339c14",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtJrsh",
    dest_anelto_password: "RwH-4f7-gCp-MmZ"
  },
  {
    group_name: "Nsight",
    office_id: "JWEN",
    office_name: "Julie A Wendt, MD, PLLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "1dbd4eca-49f2-40eb-bdae-519b9a26e085",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtJwen",
    dest_anelto_password: "RwH-4f7-gCp-c4F"
  },
  {
    group_name: "Nsight",
    office_id: "KCSP",
    office_name: "KIDNEY CARE SPECIALISTS LLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "6bf3daab-1099-43e8-a3eb-8ef98525fc24",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtKcsp",
    dest_anelto_password: "RwH-4f7-gCp-KlU"
  },
  {
    group_name: "Nsight",
    office_id: "KDHC",
    office_name: "Kidney and Hypertension Consultants, Inc",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "731256e1-75f9-46b7-b2c1-f1d707627f5d",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtKdhc",
    dest_anelto_password: "RwH-4f7-gCp-n2B"
  },
  {
    group_name: "Nsight",
    office_id: "KNPH",
    office_name: "Kansas Nephrology Physicians, PA",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "cbbda657-abe7-4924-b32f-d7d36eb30249",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtKnph",
    dest_anelto_password: "RwH-4f7-gCp-K5e"
  },
  {
    group_name: "Nsight",
    office_id: "KNTC",
    office_name: "Kantacare LLC DBA Oza Family Care and Wellness Center",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "cbbda657-abe7-4924-b32f-d7d36eb30249",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtKntc",
    dest_anelto_password: "RwH-4f7-gCp-OoB"
  },
  {
    group_name: "Nsight",
    office_id: "KSCC",
    office_name: "Kansas City Cardiology",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "58e820bf-42bc-4e07-8be2-5d228b989df9",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtKscc",
    dest_anelto_password: "RwH-4f7-gCp-VvI"
  },
  {
    group_name: "Nsight",
    office_id: "LCTM",
    office_name: "LCT Medical",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "0b4179c6-e057-4abc-9cbf-8529d9d3da0f",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtLctm",
    dest_anelto_password: "RwH-4f7-gCp-M3C"
  },
  {
    group_name: "Nsight",
    office_id: "LVWT",
    office_name: "Livingwaters Medical Clinic",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "ddfbe75f-ebba-4754-99d2-311909a67cbe",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtLvwt",
    dest_anelto_password: "RwH-4f7-gCp-B2a"
  },
  {
    group_name: "Nsight",
    office_id: "MAJM",
    office_name: "Major Medical Clinic",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "143a2bce-92f3-4ba8-8bbd-399bc85aca4c",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtMajm",
    dest_anelto_password: "RwH-4f7-gCp-PpC"
  },
  {
    group_name: "Nsight",
    office_id: "MGRZ",
    office_name: "Magued Rizkalla MD",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "e31899d5-6e03-460e-b2df-163672a16aef",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtMgrz",
    dest_anelto_password: "RwH-4f7-gCp-BbO"
  },
  {
    group_name: "Nsight",
    office_id: "MHPC",
    office_name: "MediHealth Primary Care",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "91598c8a-6532-47ea-aad5-e5ca8ebf2587",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtMhpc",
    dest_anelto_password: "RwH-4f7-gCp-SsF"
  },
  {
    group_name: "Nsight",
    office_id: "MJKT",
    office_name: "MANOJ KHATORE, MD, FACC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "383b4a3a-c352-4268-95ac-d9ccda2854f9",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtMjkt",
    dest_anelto_password: "RwH-4f7-gCp-RrE"
  },
  {
    group_name: "Nsight",
    office_id: "MLPB",
    office_name: "Melissa Lopez-Bermejo MD",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "71b78259-0ae1-482c-829d-6f2c4f7fa56d",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtMlpb",
    dest_anelto_password: "RwH-4f7-gCp-DdQ"
  },
  {
    group_name: "Nsight",
    office_id: "MLRG",
    office_name: "Marylou Romo-Gritzewsky MD",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "cf172690-4401-4797-a506-c767b5ab2ec2",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtMlrg",
    dest_anelto_password: "RwH-4f7-gCp-E1A"
  },
  {
    group_name: "Nsight",
    office_id: "MORR",
    office_name: "Morris Medical Center, PA",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "e9d2316e-485d-4ce5-adfd-6db981c03bab",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtMorr",
    dest_anelto_password: "RwH-4f7-gCp-UuH"
  },
  {
    group_name: "Nsight",
    office_id: "MTKD",
    office_name: "Mittal Kidney and Dialysis PC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "a77a868d-983c-4ab1-b9b9-389b1aec9b8d",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtMtkd",
    dest_anelto_password: "RwH-4f7-gCp-HiO"
  },
  {
    group_name: "Nsight",
    office_id: "MWCG",
    office_name: "Medical Wellness Center of Georgia",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "561cf25d-7c6c-4fc3-8708-7788af6c4cf2",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtMwcg",
    dest_anelto_password: "RwH-4f7-gCp-QqD"
  },
  {
    group_name: "Nsight",
    office_id: "NAUP",
    office_name: "Nephrology Associates of Upland and Pomona",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "a56f4cc7-2130-4c5b-bdc7-144d4393e8d4",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtNaup",
    dest_anelto_password: "RwH-4f7-gCp-P1a"
  },
  {
    group_name: "Nsight",
    office_id: "NBMC",
    office_name: "Newbern Medical Clinic",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "1865f852-25d0-4c58-86cd-6b2f5e3dfa2f",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtNbmc",
    dest_anelto_password: "RwH-4f7-gCp-TtG"
  },
  {
    group_name: "Nsight",
    office_id: "NEJM",
    office_name: "Nephrology One/ John T Morris III PC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "3a154217-e05d-404c-b0bc-cedc78f239a8",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtNejm",
    dest_anelto_password: "RwH-4f7-gCp-AaN"
  },
  {
    group_name: "Nsight",
    office_id: "NFMS",
    office_name: "North Florida Multi-Specialty Physicians",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "1c7851c4-d021-4e83-b7d3-04da1aebb32b",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtNfms",
    dest_anelto_password: "RwH-4f7-gCp-XxK"
  },
  {
    group_name: "Nsight",
    office_id: "OIMD",
    office_name: "Office of Internal Medicine PC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "d897c61a-d794-4fb5-bfc8-2896f4bb1632",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtOimd",
    dest_anelto_password: "RwH-4f7-gCp-N5E"
  },
  {
    group_name: "Nsight",
    office_id: "PAYM",
    office_name: "Payam Mehranpour Inc.",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "2bf7b7ef-aae2-4c88-9c84-281fec173f79",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtPaym",
    dest_anelto_password: "RwH-4f7-gCp-FfS"
  },
  {
    group_name: "Nsight",
    office_id: "PKCP",
    office_name: "Prime Healthcare Kansas City PhysicianServices",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "b516f7d3-b0f7-42ba-aa63-54792a0a35b7",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtPkcp",
    dest_anelto_password: "RwH-4f7-gCp-C7J"
  },
  {
    group_name: "Nsight",
    office_id: "PMNR",
    office_name: "Physical Medicine and NeuroRehabilitation PA",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "cb87cb2f-46ea-4afa-be7a-5e568555a507",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtPmnr",
    dest_anelto_password: "RwH-4f7-gCp-f2B"
  },
  {
    group_name: "Nsight",
    office_id: "PMOC",
    office_name: "Phoenix Medical Office at College Park LLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "bdcc978e-6966-4579-9ae6-8b14c6eb6668",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtPmoc",
    dest_anelto_password: "RwH-4f7-gCp-DeG"
  },
  {
    group_name: "Nsight",
    office_id: "RFRY",
    office_name: "Rommie Fakhoury MD Inc",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "1f05a4d3-ac0e-4ebb-9781-3eb60589813c",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtRfry",
    dest_anelto_password: "RwH-4f7-gCp-LmW"
  },
  {
    group_name: "Nsight",
    office_id: "RGKS",
    office_name: "Roger Kasendorf",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "332d1a58-b97e-4a87-8ce9-a7b3825001ce",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtRgks",
    dest_anelto_password: "RwH-4f7-gCp-XxK"
  },
  {
    group_name: "Nsight",
    office_id: "RMAJ",
    office_name: "Reliance Medical Associates of Jax, LLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "271b3e15-d7ae-4f15-9dd4-13970e2fbaf4",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtRmaj",
    dest_anelto_password: "RwH-4f7-gCp-C3d"
  },
  {
    group_name: "Nsight",
    office_id: "RVFM",
    office_name: "River Valley Physicians - Family Medicine 2 office",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "b6251e27-ccca-480c-8d5c-09f5b7e36499",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtRvfm",
    dest_anelto_password: "RwH-4f7-gCp-c6H"
  },
  {
    group_name: "Nsight",
    office_id: "RVLC",
    office_name: "River Valley Physicians, LLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "d28437ea-8347-44ae-bb77-b0321281b435",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtRvlc",
    dest_anelto_password: "RwH-4f7-gCp-C5g"
  },
  {
    group_name: "Nsight",
    office_id: "RVPS",
    office_name: "River Valley Physicians",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "db395636-cea9-4bb5-8194-0b8f880c86c2",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtRvps",
    dest_anelto_password: "RwH-4f7-gCp-WwJ"
  },
  {
    group_name: "Nsight",
    office_id: "SCIM",
    office_name: "Southern California Internists Medical Group",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "d9e0e5b1-e411-42e3-9174-a7dfed4fe5b0",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtScim",
    dest_anelto_password: "RwH-4f7-gCp-IjQ"
  },
  {
    group_name: "Nsight",
    office_id: "SFNC",
    office_name: "South Florida Nephrology Consultants",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "8d8043d0-19da-40e5-9793-948dd1684ce2",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtSfnc",
    dest_anelto_password: "RwH-4f7-gCp-M4d"
  },
  {
    group_name: "Nsight",
    office_id: "SJSC",
    office_name: "San Jose Clinic PA",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "790992b3-06af-4f86-b3cb-1eccf1098580",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtSjsc",
    dest_anelto_password: "RwH-4f7-gCp-YyL"
  },
  {
    group_name: "Nsight",
    office_id: "SMTR",
    office_name: "Sunil Malhotra MD LLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "9872b3ea-15f1-4176-8e19-09af779adbd4",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtSmtr",
    dest_anelto_password: "RwH-4f7-gCp-JkS"
  },
  {
    group_name: "Nsight",
    office_id: "SONI",
    office_name: "Joginder Soni MD F.A.C.C.",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "5f5dba3a-5750-4b0b-8db2-b8857351904c",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsght_Soni",
    dest_anelto_password: "RwH-4f7-gCp-aY1"
  },
  {
    group_name: "Nsight",
    office_id: "SSCR",
    office_name: "South Strand Cardiology LLC.",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "e7c5be8f-e874-418a-81af-cd1914968c8b",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtSscr",
    dest_anelto_password: "RwH-4f7-gCp-c2B"
  },
  {
    group_name: "Nsight",
    office_id: "STLV",
    office_name: "Steven J Levine MD",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "1444f274-bb4f-4353-aa7f-bea58ff81699",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtStlv",
    dest_anelto_password: "RwH-4f7-gCp-ZzM"
  },
  {
    group_name: "Nsight",
    office_id: "SWFC",
    office_name: "Southwest Family Clinic PC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "bd0f65cd-70a9-4b12-8459-6e51a654477c",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtSwfc",
    dest_anelto_password: "RwH-4f7-gCp-QoN"
  },
  {
    group_name: "Nsight",
    office_id: "SYLC",
    office_name: "Sylmara Chatman MD PC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "c4c95e5f-99b5-400f-a077-cf3ceaabc30f",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtSylc",
    dest_anelto_password: "RwH-4f7-gCp-E3c"
  },
  {
    group_name: "Nsight",
    office_id: "THSM",
    office_name: "THS Medical Clinic PA",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "7e9979fb-7349-44a3-8c8c-a8079ad8408e",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtThsm",
    dest_anelto_password: "RwH-4f7-gCp-C1A"
  },
  {
    group_name: "Nsight",
    office_id: "TRCI",
    office_name: "Tri City Internists PLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "28baad04-752b-46ae-8ac3-a87ce9f4eb37",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtTrci",
    dest_anelto_password: "RwH-4f7-gCp-b1A"
  },
  {
    group_name: "Nsight",
    office_id: "WSFM",
    office_name: "Woodstock Family Practice & Urgent Care",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "037a976c-e26d-4ddf-b40a-5c0e794bbd4d",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtWsfm",
    dest_anelto_password: "RwH-4f7-gCp-a1C"
  },
  {
    group_name: "Nsight",
    office_id: "YSRS",
    office_name: "Yaser A. Slayyeh",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "8cb31248-5875-4569-94ff-ecd728f75832",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtYsrs",
    dest_anelto_password: "RwH-4f7-gCp-EeR"
  },
  {
    group_name: "Nsight",
    office_id: "ZDCD",
    office_name: "Zudhi M Dajani Cardiology/Internal Medicine LLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "3bf3229a-c188-43dc-8676-7975c862a207",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtZdcd",
    dest_anelto_password: "RwH-4f7-gCp-d3C"
  },
  {
    group_name: "Nsight",
    office_id: "CURE",
    office_name: "Cure Cardiovascular Consultants, Inc.",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "6d7e94a8-1091-4c08-a44e-c34dce994d6d",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtCure",
    dest_anelto_password: "RwH-4f7-gCp-w1E"
  },
  {
    group_name: "Nsight",
    office_id: "LDNK",
    office_name: "Lioudmila & Nikolai Kinachtchouk M.D., PLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "77888a07-2d66-4c8e-86e3-d1e2cbac9b21",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtLdnk",
    dest_anelto_password: "RwH-4f7-gCp-X5A"
  },
  {
    group_name: "Nsight",
    office_id: "MCRD",
    office_name: "Memphis Cardiology, PLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "f1f49071-2e5a-4421-b647-8a8479f955b3",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtMcrd",
    dest_anelto_password: "RwH-4f7-gCp-Y1A"
  },
  {
    group_name: "Nsight",
    office_id: "KAHN",
    office_name: "Kidney Associates, PLLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "6eee594d-df50-466e-b36c-267adec068d9",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtKahn",
    dest_anelto_password: "RwH-4f7-gCp-Z2b"
  },
  {
    group_name: "Nsight",
    office_id: "MABR",
    office_name: "Medical Associates of Brevard",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "b97031bd-39dd-40de-9956-6542b8c7c9ea",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtMabr",
    dest_anelto_password: "RwH-4f7-gCp-CdE"
  },
  {
    group_name: "Nsight",
    office_id: "PRCA",
    office_name: "Premier Renal Care Associates LLC",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "e6cfd1d8-a317-4fd9-aab7-a0cae47c46d8",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtPrcaNonRapid",
    dest_anelto_password: "RwH-4f7-gCp-Mi7"
  },
  {
    group_name: "Nsight",
    office_id: "BDDY",
    office_name: "Badday Medical Professional Corporation",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "ff079f38-d9fd-446d-b34a-700fddd87bc1",
    source_anelto_username: "ecgNsight",
    source_anelto_password: "RwH-4f7-gCp-AcE",
    dest_anelto_username: "ecgNsghtBddy",
    dest_anelto_password: "RwH-4f7-gCp-m2B "
  },
  {
    group_name: "Nsight",
    office_id: "DMGZ",
    office_name: "G. Ryan Dominguez, M.D. ",
    contract_id: "6345cfb8a0691fd15a4bcd4d",
    organization_id: "",
    source_anelto_username: "",
    source_anelto_password: "",
    dest_anelto_username: "",
    dest_anelto_password: ""
  },
  {
    group_name: "MDRevolution",
    office_id: "ADVM",
    office_name: "Advanced Medical Center",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "5ad67e0d-b612-4dae-8288-4010f931e01c",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRAdvancedMedicalCenter",
    dest_anelto_password: "RwH-4f7-gCp-AtX"
  },
  {
    group_name: "MDRevolution",
    office_id: "APCA",
    office_name: "Advanced Pain Care",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "ef94918a-dd74-405b-b42d-c48f7b0d5432",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrApca",
    dest_anelto_password: "RwH-4f7-gCp-k4d"
  },
  {
    group_name: "MDRevolution",
    office_id: "AZPS",
    office_name: "Arizona Pulmonary Specialists ",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "6f5eb1fe-868e-4e70-b65e-d6ca667c537a",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRAZPulmonarySpecialists",
    dest_anelto_password: "RwH-4f7-gCp-giJ"
  },
  {
    group_name: "MDRevolution",
    office_id: "AIMC",
    office_name: "Arkansas Internal Medicine Clinic",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "975a8806-4128-4a28-954c-005c7af01d9a",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRArkansasInternalMedicineClinic",
    dest_anelto_password: "RwH-4f7-gCp-aUy"
  },
  {
    group_name: "MDRevolution",
    office_id: "ATHD",
    office_name: "Athena Demo",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "49ae4bbf-ff48-4953-b661-39d50e01a464",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrAthd",
    dest_anelto_password: "RwH-4f7-gCp-MnX"
  },
  {
    group_name: "MDRevolution",
    office_id: "BLNT",
    office_name: "Blount and Associates",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "8c0f0e43-bf57-48fd-b7a7-44f928f70ff2",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrBlnt",
    dest_anelto_password: "RwH-4f7-gCp-K3c"
  },
  {
    group_name: "MDRevolution",
    office_id: "CPTL",
    office_name: "Capital Cardiology",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "a96631aa-e269-441f-8719-9b7f09ae8a86",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrCptl",
    dest_anelto_password: "RwH-4f7-gCp-j4D"
  },
  {
    group_name: "MDRevolution",
    office_id: "CDBE",
    office_name: "Capital Diabetes and Endocrine",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "982a3086-b400-42f8-ba6a-3f598683a417",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrCdbe",
    dest_anelto_password: "RwH-4f7-gCp-K2B"
  },
  {
    group_name: "MDRevolution",
    office_id: "CRSL",
    office_name: "Cardiac Solutions",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "e7ddaabd-68e1-4b87-abca-45bfdcb58983",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRCardiacSolutions",
    dest_anelto_password: "RwH-4f7-gCp-WX5"
  },
  {
    group_name: "MDRevolution",
    office_id: "CMGP",
    office_name: "Carson Medical Group",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "0abc7acd-0695-495d-98d8-d053d1f647b2",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRCarsonMedGroup",
    dest_anelto_password: "RwH-4f7-gCp-ARU"
  },
  {
    group_name: "MDRevolution",
    office_id: "CART",
    office_name: "Carteret Medical Group",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "fae3dc80-5410-4089-8fd6-bcc901742f45",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRCarteretMedGroup",
    dest_anelto_password: "RwH-4f7-gCp-fsW"
  },
  {
    group_name: "MDRevolution",
    office_id: "CHDC",
    office_name: "Chandra Diagnostic Cardiology",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "7fa01f36-5662-42b0-a52f-a41cb5f9aa68",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRChandraDiagnosticCardiology",
    dest_anelto_password: "RwH-4f7-gCp-DWy"
  },
  {
    group_name: "MDRevolution",
    office_id: "CHCI",
    office_name: "Community Health Centers, Inc.",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "aaa44bb6-51c4-4610-b9a2-156207bb39c4",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRCommunityHealthCenters",
    dest_anelto_password: "RwH-4f7-gCp-iqH"
  },
  {
    group_name: "MDRevolution",
    office_id: "CORH",
    office_name: "Cor Health",
    contract_id: "63c829fd212b4bf778e530b7",
    organization_id: "0d949ae3-bcca-4f0a-8573-59b605f3c89f",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRCorHealth",
    dest_anelto_password: "RwH-4f7-gCp-AvZ"
  },
  {
    group_name: "MDRevolution",
    office_id: "CSLD",
    office_name: "Costa Salud Community Health Centers",
    contract_id: "63c829fd212b4bf778e530b7",
    organization_id: "3b1832fe-c0d9-4918-b0ab-ff9df24571ab",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRCostaSaludCommunityHealthCenters",
    dest_anelto_password: "RwH-4f7-gCp-aWa"
  },
  {
    group_name: "MDRevolution",
    office_id: "DYIM",
    office_name: "Dayton Internal Medicine",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "e4e62855-3d11-4e0d-a38b-6c28cf1b2608",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrDYIM",
    dest_anelto_password: "RwH-4f7-gCp-L8U"
  },
  {
    group_name: "MDRevolution",
    office_id: "DMCP",
    office_name: "DMC Primary Care",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "93fe2a95-d0ab-4f6d-8467-cfe5527bb771",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRDMCPrimaryCare",
    dest_anelto_password: "RwH-4f7-gCp-IFj"
  },
  {
    group_name: "MDRevolution",
    office_id: "DRHL",
    office_name: "Doctors Home Line",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "d0a8fd40-1d32-4c1a-804e-3bf5c9113025",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrDrhl",
    dest_anelto_password: "RwH-4f7-gCp-j2B"
  },
  {
    group_name: "MDRevolution",
    office_id: "CTEST",
    office_name: "ECG TEST GROUP",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "11b0cce0-781b-434c-b487-da9dbbaa79e3",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrCtest",
    dest_anelto_password: "RwH-4f7-gCp-k1A"
  },
  {
    group_name: "MDRevolution",
    office_id: "EMPU",
    office_name: "Empower U Community Health Center",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "d38bc6b0-684b-444f-8d34-c88777162430",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDREmpowerUCommHC",
    dest_anelto_password: "RwH-4f7-gCp-EPp"
  },
  {
    group_name: "MDRevolution",
    office_id: "MPSF",
    office_name: "Family Medicine Partners of Santa Fe",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "47b2de1f-2ef0-436f-9707-f0412a897ece",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRFamilyMedicinePartnersSantaFe",
    dest_anelto_password: "RwH-4f7-gCp-Yvp"
  },
  {
    group_name: "MDRevolution",
    office_id: "GNDL",
    office_name: "Gary Nudell, SC",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "4741b45e-7d99-4f55-b503-e32efa5296e6",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRGaryNudellSC",
    dest_anelto_password: "RwH-4f7-gCp-6UX"
  },
  {
    group_name: "MDRevolution",
    office_id: "GRMC",
    office_name: "Gerald Champion Regional Medical Center",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "ce806a4a-6524-4870-9228-e2f68ee0a541",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrGrmc",
    dest_anelto_password: "RwH-4f7-gCp-J3c"
  },
  {
    group_name: "MDRevolution",
    office_id: "GVLY",
    office_name: "Green Valley Primary Care",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "2c85ed29-d26c-4c64-8a56-935952f46b6f",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRGreenValleyPrimaryCare",
    dest_anelto_password: "RwH-4f7-gCp-DbQ"
  },
  {
    group_name: "MDRevolution",
    office_id: "GIDM",
    office_name: "Greenway Intergy Demo",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "a928cdc9-06d7-4bac-97ab-2ac81d698860",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrGidm",
    dest_anelto_password: "RwH-4f7-gCp-NoY"
  },
  {
    group_name: "MDRevolution",
    office_id: "GPDM",
    office_name: "Greenway PrimeSuite Demo",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "7b1df8dc-58f0-4e7d-961c-bc0d3b3506f5",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRGreenwayPrimeSuiteDemo",
    dest_anelto_password: "RwH-4f7-gCp-PvU"
  },
  {
    group_name: "MDRevolution",
    office_id: "HMLT",
    office_name: "Hamilton Cardiology Associates",
    contract_id: "63c82e9a212b4bf778e530c7",
    organization_id: "30bac26b-f9b2-4009-a8c7-e906f8f8d8b9",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRHamiltonCardiologyAssociates",
    dest_anelto_password: "RwH-4f7-gCp-AxB"
  },
  {
    group_name: "MDRevolution",
    office_id: "IDKD",
    office_name: "Idaho Kidney Institute",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "47e6f9a2-3bd2-434c-9add-b74485027128",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrIdkd",
    dest_anelto_password: "RwH-4f7-gCp-J1A"
  },
  {
    group_name: "MDRevolution",
    office_id: "JKSN",
    office_name: "Jackson Pulmonary Associates, P.A.",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "49294824-ed93-4232-ae48-f46d0aad8165",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRJacksonPulmonaryAssocPA",
    dest_anelto_password: "RwH-4f7-gCp-tTp"
  },
  {
    group_name: "MDRevolution",
    office_id: "GDMN",
    office_name: "Jeffrey Goodman MD",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "0a396b96-b795-4584-9107-4e4b75ad79da",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRJeffreyGoodmanMD",
    dest_anelto_password: "RwH-4f7-gCp-Edb"
  },
  {
    group_name: "MDRevolution",
    office_id: "KATY",
    office_name: "Katy Medical Center",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "f501ad2c-2091-4483-bb6a-aa9c963653d8",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrKaty",
    dest_anelto_password: "RwH-4f7-gCp-OpB"
  },
  {
    group_name: "MDRevolution",
    office_id: "LCYM",
    office_name: "Lake County Medical",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "3fadd4fc-d713-4c1e-9df7-8b8c93e833e6",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRLakeCountyMed",
    dest_anelto_password: "RwH-4f7-gCp-cvh"
  },
  {
    group_name: "MDRevolution",
    office_id: "LVEN",
    office_name: "Las Vegas Endocrinology",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "021b5761-5ad2-4aae-90a6-414f1709360c",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRLVEndocrinology",
    dest_anelto_password: "RwH-4f7-gCp-uYA"
  },
  {
    group_name: "MDRevolution",
    office_id: "LASN",
    office_name: "Las Vegas Neurology Center",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "51844fad-7dbf-4ade-b2b6-3d3c19943726",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrLasn",
    dest_anelto_password: "RwH-4f7-gCp-QrF"
  },
  {
    group_name: "MDRevolution",
    office_id: "LORI",
    office_name: "Lori Gautreaux",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "7dd6879f-aa4a-4dbc-b7bf-ae929d3e83b2",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrLori",
    dest_anelto_password: "RwH-4f7-gCp-PqD"
  },
  {
    group_name: "MDRevolution",
    office_id: "LAHS",
    office_name: "Los Angeles Heart Specialists",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "679bad22-0dd0-48c1-bffb-b9c4c6c053eb",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRLAHeartSpecialists",
    dest_anelto_password: "RwH-4f7-gCp-wZL"
  },
  {
    group_name: "MDRevolution",
    office_id: "TSTM",
    office_name: "MD Revolution",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "149bde0e-ff1b-490c-8ea1-ad0d8a2915b6",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRevolution",
    dest_anelto_password: "RwH-4f7-gCp-OoQ"
  },
  {
    group_name: "MDRevolution",
    office_id: "MDRT",
    office_name: "MDR Testing",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "152fb600-09e4-40f1-9e9c-31cc5e056ae7",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrMdrt",
    dest_anelto_password: "RwH-4f7-gCp-h5E"
  },
  {
    group_name: "MDRevolution",
    office_id: "MWCH",
    office_name: "MDWatch",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "e8064bae-4f00-4558-9962-b14fd52f9412",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRMDWatch",
    dest_anelto_password: "RwH-4f7-gCp-TiQ"
  },
  {
    group_name: "MDRevolution",
    office_id: "MELB",
    office_name: "Methodist Le Bonheur",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "ba59f941-3d21-40f0-9f4d-493554d2b78f",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRMethodist",
    dest_anelto_password: "RwH-4f7-gCp-FHW"
  },
  {
    group_name: "MDRevolution",
    office_id: "MDLD",
    office_name: "Midlands Pulmonary",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "661928d3-b2ab-46be-b0f8-5c071bc7b9e2",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrMdld",
    dest_anelto_password: "RwH-4f7-gCp-H1a"
  },
  {
    group_name: "MDRevolution",
    office_id: "MGTL",
    office_name: "Mitchell Gittelman, D.O. P.A.",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "a1910634-03d1-4e28-b82e-337f8ccf1036",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrMgtl",
    dest_anelto_password: "RwH-4f7-gCp-h2B"
  },
  {
    group_name: "MDRevolution",
    office_id: "NEFI",
    office_name: "Northeast Florida Internal Medical",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "beeea7ed-79b4-4091-bc07-d91226b121f0",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRNortheastFLInternalMed",
    dest_anelto_password: "RwH-4f7-gCp-fEd"
  },
  {
    group_name: "MDRevolution",
    office_id: "NOVO",
    office_name: "Novo Wellness",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "183557ff-05ed-4341-a4d6-aa5e2fe2c3f9",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrNovo",
    dest_anelto_password: "RwH-4f7-gCp-RsH"
  },
  {
    group_name: "MDRevolution",
    office_id: "OLYM",
    office_name: "Olympic Internal Medicine",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "ec24ee71-aa6c-4f10-8eb1-ef16a8480f0b",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDROlympicInternalMedicine",
    dest_anelto_password: "RwH-4f7-gCp-jbE"
  },
  {
    group_name: "MDRevolution",
    office_id: "OSBN",
    office_name: "Osborn Family Health Center",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "34d8e38c-10cf-4bf9-ae04-855eeec5e42a",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrOsbn",
    dest_anelto_password: "RwH-4f7-gCp-StJ"
  },
  {
    group_name: "MDRevolution",
    office_id: "PTNR",
    office_name: "Partner MD",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "319aad7a-5588-4a42-89dd-c5222c7514cb",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRPartnerMD",
    dest_anelto_password: "RwH-4f7-gCp-bxz"
  },
  {
    group_name: "MDRevolution",
    office_id: "PRIM",
    office_name: "Prime Care Physicians",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "4501c4f7-a587-495a-a280-5676af7354bc",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRPrimeCarePhysicians",
    dest_anelto_password: "RwH-4f7-gCp-tgb"
  },
  {
    group_name: "MDRevolution",
    office_id: "PRMD",
    office_name: "Prime Medical",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "49e1ae18-1bc5-4ad6-9c0b-c34211d2e9d4",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRPrimeMedical",
    dest_anelto_password: "RwH-4f7-gCp-Vlc"
  },
  {
    group_name: "MDRevolution",
    office_id: "ARRW",
    office_name: "Redirect Health",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "9ca66c4c-abc0-45af-81f4-edc4dcb95d6c",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRRedirectHealth",
    dest_anelto_password: "RwH-4f7-gCp-IZG"
  },
  {
    group_name: "MDRevolution",
    office_id: "SHOR",
    office_name: "Shore Heart Group LLC",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "725da48c-00ea-428d-87c1-f38eb5232b0c",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrShor",
    dest_anelto_password: "RwH-4f7-gCp-h2c"
  },
  {
    group_name: "MDRevolution",
    office_id: "SDFP",
    office_name: "Stephen G. Diamantoni & Assoc. Family Practice",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "dbd52ce8-f997-428e-aff1-b5e303b25928",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRStephenDiamantoniAssocFamPractice",
    dest_anelto_password: "RwH-4f7-gCp-6kp"
  },
  {
    group_name: "MDRevolution",
    office_id: "TXLF",
    office_name: "Texas Center for Lifestyle Medicine",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "e95da8a3-157b-4780-acc1-6cf670c10029",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRTX_CTR_For_LifestyleMed",
    dest_anelto_password: "RwH-4f7-gCp-EZk"
  },
  {
    group_name: "MDRevolution",
    office_id: "NJSS",
    office_name: "The Medical Group of New Jersey-Sussex Cardiology",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "18dbc8a0-2e7a-41bd-9ba4-af2ab0814ddf",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrNjss",
    dest_anelto_password: "RwH-4f7-gCp-H4d"
  },
  {
    group_name: "MDRevolution",
    office_id: "TSFM",
    office_name: "Trinity Family and Sports Medicine",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "09e1c1bb-d8f6-454c-8dbb-e9b5eb6a517d",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrTsfm",
    dest_anelto_password: "RwH-4f7-gCp-7yZ"
  },
  {
    group_name: "MDRevolution",
    office_id: "TZLB",
    office_name: "Tumasz and Lobianco PC",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "2815d622-9057-48c6-87fe-02c94ca073cc",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMdrTzlb",
    dest_anelto_password: "RwH-4f7-gCp-TuL"
  },
  {
    group_name: "MDRevolution",
    office_id: "WWMD",
    office_name: "Western Washington Medical Group",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "b1c22ce8-c29e-41bc-926c-0d30b4a73a9e",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRWesternWashingtonMedGroup",
    dest_anelto_password: "RwH-4f7-gCp-PoL"
  },
  {
    group_name: "MDRevolution",
    office_id: "WCHS",
    office_name: "Winchester Internal Medicine",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "3e614855-e8e2-4e7e-8edb-7889be945d05",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRWinchesterInternalMed",
    dest_anelto_password: "RwH-4f7-gCp-YGm"
  },
  {
    group_name: "MDRevolution",
    office_id: "ZION",
    office_name: "Zion Urgent Care Clinic",
    contract_id: "62fbcf7a9b5c5f5e84cc520e",
    organization_id: "c57d3b38-c323-45fa-a51d-78fe5ae7ff02",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMDRZionUrgentCareClinic",
    dest_anelto_password: "RwH-4f7-gCp-X4P"
  },
  {
    group_name: "ZiaHealthcare",
    office_id: "ARVD",
    office_name: "Arvada West Family Medicine",
    contract_id: "63d2ef18212b4bf778e53195",
    organization_id: "38bd9592-0f6a-45d1-a399-3e51a50f6da9",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgZHMArvadaWestFamilyMedicine",
    dest_anelto_password: "RwH-4f7-gCp-NnA"
  },
  {
    group_name: "ZiaHealthcare",
    office_id: "EAMD",
    office_name: "Elena Anisimova, MD",
    contract_id: "63d2ef18212b4bf778e53195",
    organization_id: "d7b4ee16-5a3e-41d7-a295-957cb8f3dcd8",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgZHMElenaAnisimovaMD",
    dest_anelto_password: "RwH-4f7-gCp-AyE"
  },
  {
    group_name: "ZiaHealthcare",
    office_id: "EVMC",
    office_name: "Evans Medical Center",
    contract_id: "63d2ef18212b4bf778e53195",
    organization_id: "d2ee69eb-9dc6-4c23-a8f7-30a263339a14",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgZHMEvansMedicalCenter",
    dest_anelto_password: "RwH-4f7-gCp-BxA"
  },
  {
    group_name: "ZiaHealthcare",
    office_id: "LFPC",
    office_name: "La Familia Primary Care",
    contract_id: "63d2ef18212b4bf778e53195",
    organization_id: "9511d502-0850-4ba8-87c0-eb5cb92c22e0",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgZHMLaFamiliaPrimaryCare",
    dest_anelto_password: "RwH-4f7-gCp-OoB"
  },
  {
    group_name: "ZiaHealthcare",
    office_id: "MBFP",
    office_name: "Mark Baravik FNP LLC Family Practice",
    contract_id: "63d2ef18212b4bf778e53195",
    organization_id: "247508f9-880e-49ee-afc6-05b882fa6681",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgZHMBaravikFamilyPractice",
    dest_anelto_password: " RwH-4f7-gCp-DRs"
  },
  {
    group_name: "ZiaHealthcare",
    office_id: "PFAM",
    office_name: "Premier Family Medicine",
    contract_id: "63d2ef18212b4bf778e53195",
    organization_id: "c9e98df9-f17b-43f4-89c2-d16781b0cd87",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgZHMPremierFamilyMedicine",
    dest_anelto_password: "RwH-4f7-gCp-PpC"
  },
  {
    group_name: "ZiaHealthcare",
    office_id: "ZIAP",
    office_name: "Private Pay Clients",
    contract_id: "63d2ef18212b4bf778e53195",
    organization_id: "456c4c76-58a1-4c6a-bb05-c2fb2576666b",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgZHMPrivatePayPatients",
    dest_anelto_password: "RwH-4f7-gCp-RrE"
  },
  {
    group_name: "ZiaHealthcare",
    office_id: "RTFM",
    office_name: "Raton Family Medicine",
    contract_id: "63d2ef18212b4bf778e53195",
    organization_id: "68332b99-5c4f-4d1d-b55c-b14ba3ca3350",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgZHMRatonFamilyMedicine",
    dest_anelto_password: "RwH-4f7-gCp-FxX"
  },
  {
    group_name: "ZiaHealthcare",
    office_id: "SDVP",
    office_name: "South Denver Physicians, PLLC",
    contract_id: "63d2ef18212b4bf778e53195",
    organization_id: "b1bf711b-cc44-415a-a037-0faeb8c9756b",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgZHMSouthDenverPhysicians",
    dest_anelto_password: "RwH-4f7-gCp-hVJ"
  },
  {
    group_name: "ZiaHealthcare",
    office_id: "STKR",
    office_name: "Stephanie K. Kraft MD, MPH",
    contract_id: "63d2ef18212b4bf778e53195",
    organization_id: "2fb46097-d1fd-426b-89a5-957cae5a5215",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgZHMStephanieKraftMD",
    dest_anelto_password: "RwH-4f7-gCp-QqD"
  },
  {
    group_name: "ECGZia",
    office_id: "BROM",
    office_name: "Birmingham Royal Oak Medical Group",
    contract_id: "62e95cf8a960d5ebe4567148",
    organization_id: "04768ebc-0604-43e9-ade6-76a67a4039c1",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgBirminghamRoyalOakMedicalGroup",
    dest_anelto_password: "RwH-4f7-gCp-MmW"
  },
  {
    group_name: "ECGZia",
    office_id: "BSLD",
    office_name: "Buena Salud Family Medicine LLC",
    contract_id: "62e98603a960d5ebe456718f",
    organization_id: "30ab4284-e83f-45e6-92eb-153c3b09ae62",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgBuenaSalud",
    dest_anelto_password: "RwH-4f7-gCp-BsD"
  },
  {
    group_name: "ECGZia",
    office_id: "CMMC",
    office_name: "Cimmaron Healthcare Clinic",
    contract_id: "62ec009cf6171c1299c79ca6",
    organization_id: "0c17d9f2-a1b0-414f-ae05-bf96c7c5e5e3",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgCimarronHealthcareClinic",
    dest_anelto_password: "RwH-4f7-gCp-pIr"
  },
  {
    group_name: "ECGZia",
    office_id: "FPAT",
    office_name: "Family Practice Associates of Taos - Taos, NM",
    contract_id: "62e94148a960d5ebe4567135",
    organization_id: "115e184f-b86b-48a2-aeba-05e581c59281",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgFamilyPracticeAssocTaos",
    dest_anelto_password: "RwH-4f7-gCp-aGN"
  },
  {
    group_name: "ECGZia",
    office_id: "INTH",
    office_name: "In Touch Health - Philadelphia, MS",
    contract_id: "62ec270ef6171c1299c79cf4",
    organization_id: "531c176d-6b0a-4c2a-a7bd-43f4e21b6a8d",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgInTouchHealth",
    dest_anelto_password: "RwH-4f7-gCp-AmQ"
  },
  {
    group_name: "ECGZia",
    office_id: "LSAR",
    office_name: "Lisa Robles MD",
    contract_id: "63ff7b8101327ce5ec2d78b9",
    organization_id: "a3789d04-d32f-41c3-830d-c427d9515121",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgLisaRoblesMD",
    dest_anelto_password: "Rwh-4f7-gCp-uG6"
  },
  {
    group_name: "ECGZia",
    office_id: "MVLY",
    office_name: "Moreno Valley Healthcare Clinic",
    contract_id: "62ec12eef6171c1299c79cb9",
    organization_id: "a735f592-2742-44f9-ab1b-23f0b18f4140",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgMorenoValley",
    dest_anelto_password: "RwH-4f7-gCp-RP8"
  },
  {
    group_name: "ECGZia",
    office_id: "PRMG",
    office_name: "Premier Medical Group - Kosciusko, MS",
    contract_id: "62eac8aff6171c1299c79c7f",
    organization_id: "c748a726-0b7c-4af7-bf2c-8dbd8b688380",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgPremierMedicalGroupMS",
    dest_anelto_password: "RwH-4f7-gCp-UB7"
  },
  {
    group_name: "ECGZia",
    office_id: "SCFM",
    office_name: "Schreiber Family Medicine LLC",
    contract_id: "62eacf38f6171c1299c79c92",
    organization_id: "fb6bdff8-23c0-4e3f-acff-4b4120610db8",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgSchreiberFamilyMedicine",
    dest_anelto_password: "RwH-4f7-gCp-QLs"
  },
  {
    group_name: "ECGZia",
    office_id: "TCPL",
    office_name: "Thirlby Clinic, PLC",
    contract_id: "62ec16bcf6171c1299c79cce",
    organization_id: "99f71837-f413-4b6f-9eec-44db21ad7e7f",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgThirlbyClinicPLC",
    dest_anelto_password: "RwH-4f7-gCp-aLP"
  },
  {
    group_name: "ECGZia",
    office_id: "TCTU",
    office_name: "Total Care 2U - Conroe, TX",
    contract_id: "62ec1e37f6171c1299c79ce1",
    organization_id: "1132fb73-d043-449f-bdc6-a82c0f305d2c",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgTotalCare2U",
    dest_anelto_password: "RwH-4f7-gCp-tXL"
  },
  {
    group_name: "ECGZia",
    office_id: "CCPI",
    office_name: "Connected Care Partners of Illinois",
    contract_id: "6310d445612e6892cb4d0f81",
    organization_id: "07075fef-4c3b-4c8b-a4cd-84bd038fb29d",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgConnectedCarePartnersofIL",
    dest_anelto_password: "RwH-4f7-gCp-TmZ"
  },
  {
    group_name: "ECGZia",
    office_id: "ORTG",
    office_name: "Ortega Wellness",
    contract_id: "62e1a5f5a960d5ebe456708d",
    organization_id: "06ab9750-9fe2-4b8e-88a3-35c33e853520",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgOrtegaWellness",
    dest_anelto_password: "RwH-4f7-gCp-F3k"
  },
  {
    group_name: "ECGZia",
    office_id: "MNTE",
    office_name: "Manatee Senior Care",
    contract_id: "62feb4fe612e6892cb4d0d84",
    organization_id: "4892522b-d8e6-4860-9691-6492bc67eebf",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgManateeSeniorCare",
    dest_anelto_password: "RwH-4f7-gCp-aSw"
  },
  {
    group_name: "ECGZia",
    office_id: "RVBD",
    office_name: "Riverbend Healthcare",
    contract_id: "6308fd5a612e6892cb4d0ed7",
    organization_id: "82a83a1e-fe87-42ed-9bfa-831b40d65d98",
    source_anelto_username: "ElectronicCaregiver",
    source_anelto_password: "RwH-4f7-gCp-Ymh",
    dest_anelto_username: "ecgRiverbendHealthcare",
    dest_anelto_password: "RwH-4f7-gCp-pTx"
  }
]